# Generated by Django 5.2.4 on 2025-08-04 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Каткгория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, verbose_name='URL')),
                ('alcohol_type', models.CharField(choices=[('vodka', 'Водка'), ('whiskey', 'Виски'), ('cognac', 'Коньяк'), ('wine', 'Вино'), ('beer', 'Пиво'), ('champagne', 'Шампанское'), ('liqueur', 'Ликер'), ('tequila', 'Текила'), ('rum', 'Ром'), ('gin', 'Джин'), ('other', 'Другое')], max_length=20, verbose_name='Тип алкоголя')),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('country', models.CharField(max_length=100, verbose_name='Страна производства')),
                ('volume', models.DecimalField(decimal_places=2, help_text='В литрах', max_digits=5, verbose_name='Объем')),
                ('strength', models.DecimalField(decimal_places=1, help_text='в процентах', max_digits=4, verbose_name='Крепость')),
                ('description', models.TextField(max_length=300, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('stock', models.PositiveIntegerField(verbose_name='Количество на складе')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='Изображение')),
                ('categoru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='menu.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['id', 'slug'], name='menu_produc_id_c15663_idx')],
            },
        ),
    ]
